### ISSUE TITLE
How did you install dronekit/pymavlink ?

### ISSUE THREAD

**Issue by AndKe** [patrickpoirier51/JeVois--Python-Tracking#3]
subject says all..

**Comment by patrickpoirier51** [comment]
Unlike OpenMV, there is no implementation on JeVOIS but it can be done if you are eager to install the dev. toolkit … at the time it was kreepy :smiley:

Otherwise you run a python script on a pi Zero using pymavlink like I did

**Comment by AndKe** [comment]
oh - sorry - first now I understand that you did not run it all inside JeVois  :)

**Comment by ela37** [comment]
I am trying to get the JeVois to work with Pickhawk, you give me a howto setup Pymavlink on a raspberry pi zero
